### ISSUE TITLE
Firewalld incorrectly detected as iptables with no active rules

### ISSUE THREAD

**Issue by daniejstriata** [CISOfy/lynis#461]
From my report I see that the firewall on Centos 7.3 is being reported as follows:
```
firewall_software[]=iptables
warning[]=FIRE-4512|iptables module(s) loaded, but no rules active|-|-|
firewall_active=1
firewall_empty_ruleset=1
firewall_installed=1
firewall_software=iptables
```
The OS is using FirewallD instead and it does have rules I can see when I run:
```
# firewall-cmd --zone=dmz --list-all
dmz
 target: default
 icmp-block-inversion: no
 interfaces:
 sources:
 services: http https ntp ssh
 ports:
 protocols:
 masquerade: no
 forward-ports:
 sourceports:
 icmp-blocks: echo-reply
 rich rules:
```
under services you can see that it allows _http https ntp ssh_
