### ISSUE TITLE
Ubuntu 18.04 NetPlan - problem with 2 responsive nameservers 

### ISSUE THREAD

**Issue by Vilican** [CISOfy/lynis#545]
Ubuntu 18.04 uses NetPlan + DNSMasq to configure networking and nameservers.

For example, my `/etc/netplan/01-netcfg.yaml` looks like this (IPs and domains changed):

```
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.1.2/24]
      gateway4: 192.168.1.1
      nameservers:
        search: [example.net]
        addresses: [192.168.1.1,8.8.8.8]
```

In `resolv.conf` is added only localhost (`nameserver 127.0.0.53`). Any changes gets overwritten.

So, although I do actually have 2 responsive nameservers, I am still getting red warning NETW-2705.
